# -*- coding: utf-8 -*-
"""Milestone 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q3gVY3X3u25IJLDlHyrS2gH8hltq3Bc6

installing required libraries
"""

pip install pytest

"""installing required libraries"""

pip install google-search-results

"""Importing google search images"""

from serpapi import GoogleSearch
import os, json

"""Results of the images"""

image_results = []

for query in ["Toilets"]:
    params = {
        "engine": "google",               # search engine. Google, Bing, Yahoo, Naver, Baidu...
        "q": query,                       # search query
        "tbm": "isch",                    # image results
        "num": "100",                     # number of images per page
        "ijn": 0,                         # page number: 0 -> first page, 1 -> second...
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   # your serpapi api key
    }

    search = GoogleSearch(params)         # where data extraction happens

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       # JSON -> Python dictionary

        # checks for "Google hasn't returned any results for this query."
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            # update to the next page
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""results of the images"""

image_results = []

for query in ["Bathroom Sinks"]:
    params = {
        "engine": "google",              
        "q": query,                       
        "tbm": "isch",                    
        "num": "100",                     
        "ijn": 0,                        
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)        
    images_is_present = True
    while images_is_present:
        results = search.get_dict()       

      
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Results of ShowerHead images"""

image_results = []

for query in ["Showerheads"]:
    params = {
        "engine": "google",               
        "q": query,                      
        "tbm": "isch",                   
        "num": "100",                  
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         # where data extraction happens

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       # JSON -> Python dictionary

        # checks for "Google hasn't returned any results for this query."
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            # update to the next page
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Rsults of Bathroom tile images"""

image_results = []

for query in ["Bathroom Tile"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                    
        "num": "100",                     
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         # where data extraction happens

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       # JSON -> Python dictionary

        # checks for "Google hasn't returned any results for this query."
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            # update to the next page
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Results of Vanities images"""

image_results = []

for query in ["Vanities"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                    
        "num": "100",                     
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       

       
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Generated Faucets images"""

image_results = []

for query in ["Faucets"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                    
        "num": "100",                     
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       

        
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Images of lighting"""

image_results = []

for query in ["Lighting"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                    
        "num": "100",                    
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()      

        
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Images of cabinets and Storage"""

image_results = []

for query in ["Cabinets & Storage"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                   
        "num": "100",                     
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()      

        
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Images of bathtubs and Whirlpools"""

image_results = []

for query in ["Bathtubs and Whirlpools"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                     
        "num": "100",                     
        "ijn": 0,                         
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       

        
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
           
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

"""Reuults of Showers"""

image_results = []

for query in ["Showers"]:
    params = {
        "engine": "google",               
        "q": query,                       
        "tbm": "isch",                   
        "num": "100",                     
        "ijn": 0,                         # 
        "api_key":("7981ea25ecca5cd1a09a815df3c8c1d9153924808ea2fe60ccd165ce1aa6680e")   
    }

    search = GoogleSearch(params)         

    images_is_present = True
    while images_is_present:
        results = search.get_dict()       

        
        if "error" not in results:
            for image in results["images_results"]:
                if image["original"] not in image_results:
                    print(image["original"])
                    image_results.append(image["original"])
            
            
            params["ijn"] += 1
        else:
            images_is_present = False
            print(results["error"])

print(json.dumps(image_results, indent=2))
print(len(image_results))

